spring.application.name=Projet-Cad-Optique


#spring.datasource.url=jdbc:postgresql://localhost:5432/cad_app
#spring.datasource.username=postgres
#spring.datasource.password=InfoBase24..

spring.datasource.url=jdbc:postgresql://ep-square-wildflower-ay5wlu0r-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2qSxl0hruADI

#Hibernate met à jour le schéma DB automatiquement au démarrage
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Montrer les requettes excutes en console
spring.jpa.show-sql=true

# Format SQL for better readability
spring.jpa.properties.hibernate.format_sql=true

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=cadOptique

frontend.url=http://localhost:5173


project.image=images/
image.base.url=http://localhost:8080/images

whatsapp.api.token=EAAZAkeil0xB4BSDZB2MVdhBSevVQZAo1EHv3pbiOQByYlQkIpMieo8tKGieAN7K8nipKN9m61KWW87vvrLCVXFdFETUcvZCv62BUkPPJqxZB5Rt0rn2H08gQZACnZBxydpYfjEOuaAyZARpoqJoLKKY0Vis6BAFoiglIHB7PVH86b9A8PRFTAQRqEoc2Px0YYeS6EvH7BYwJNmsYKkdp8y1gRQk3YsxNo83E50UZALbi3wXNvELrs3I2v9NZAd06oJDOwfAQpqRIfWCjOoLn1XZCvVmqSpjal6pdQHHYgo8VQZDZD
whatsapp.phone.number.id=1196167050254244
whatsapp.api.url=https://graph.facebook.com/v25.0

google.vision.api.key=AIzaSyD1lR3AXWyp04www_ZTwu9IImxRoluUU-I



