spring.application.name=Projet-Cad-Optique


#spring.datasource.url=jdbc:postgresql://localhost:5432/cad_app
#spring.datasource.username=postgres
#spring.datasource.password=InfoBase24..



#Hibernate met à jour le schéma DB automatiquement au démarrage
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Montrer les requettes excutes en console
spring.jpa.show-sql=true

# Format SQL for better readability
spring.jpa.properties.hibernate.format_sql=true


spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=cadOptique

whatsapp.phone.number.id=1196167050254244
whatsapp.api.url=https://graph.facebook.com/v25.0

project.image=images/



#Secrets

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.app.jwtSecret=${JWT_SECRET}
frontend.url=${FRONTEND_URL}
image.base.url=${IMAGE_BASE_URL}
whatsapp.api.token=${WHATSAPP_API_TOKEN}
google.vision.api.key=${GOOGLE_VISION_API_KEY}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}

cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}



